# Generated by Django 3.2.1 on 2024-04-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='k8s_node',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
