# Generated by Django 3.2.1 on 2024-04-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8sDeploy', '0002_k8s_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8s_node',
            name='config',
            field=models.CharField(default='hellowolrd', max_length=255, unique=True, verbose_name='配置'),
        ),
    ]
