# Generated by Django 3.2.1 on 2024-04-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8sDeploy', '0003_k8s_node_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k8s_node',
            name='config',
            field=models.TextField(default='hellowolrd', max_length=255, unique=True, verbose_name='配置'),
        ),
    ]
