# Generated by Django 3.2.1 on 2024-04-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8sDeploy', '0005_auto_20240402_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='k8s_cluster_create',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='hellowolrd', max_length=255, unique=True, verbose_name='名字')),
            ],
            options={
                'verbose_name': '集群创建',
                'verbose_name_plural': '集群创建',
            },
        ),
        migrations.AlterModelOptions(
            name='k8s_master',
            options={'verbose_name': '添加master', 'verbose_name_plural': '添加master'},
        ),
        migrations.AlterModelOptions(
            name='k8s_node',
            options={'verbose_name': '添加node', 'verbose_name_plural': '添加node'},
        ),
        migrations.AddField(
            model_name='k8s_master',
            name='name',
            field=models.CharField(default='hellowolrd', max_length=255, unique=True, verbose_name='名字'),
        ),
    ]
