# Generated by Django 3.2.1 on 2024-04-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0076_taskenc_taskenctaskcreate'),
        ('k8sDeploy', '0006_auto_20240402_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8s_cluster_create',
            name='Host',
            field=models.ManyToManyField(to='ConfCen.HostConfig'),
        ),
        migrations.AlterField(
            model_name='k8s_cluster_create',
            name='name',
            field=models.CharField(default='集群名字', max_length=255, unique=True, verbose_name='名字'),
        ),
    ]
