# Generated by Django 3.2.1 on 2024-04-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8sDeploy', '0007_auto_20240402_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8s_cluster_create',
            name='types',
            field=models.CharField(choices=[('正式集群', '正式集群'), ('测试集群', '测试集群')], default=0, max_length=255, verbose_name='类型'),
        ),
    ]
