# Generated by Django 3.2.1 on 2024-04-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('k8sDeploy', '0008_k8s_cluster_create_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='k8s_cluster_create',
            name='Host',
        ),
    ]
