# Generated by Django 3.2.1 on 2023-10-23 13:41

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDocuments',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='cloud7', max_length=255, unique=True, verbose_name='标题')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '帮助文档',
                'verbose_name_plural': '帮助文档',
            },
        ),
    ]
