# Generated by Django 3.2.1 on 2024-05-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ConfCen', '0076_taskenc_taskenctaskcreate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projdep',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='项目名字')),
                ('cid', models.CharField(blank=True, max_length=255, null=True, verbose_name='cid')),
                ('log_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='log_id')),
                ('ConfigContent', models.TextField(blank=True, null=True, verbose_name='配置内容')),
                ('TaskEnc_select_Custom_Env', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_TaskEnc_select_Custom_Env', to='ConfCen.taskenc', verbose_name='任务封装')),
            ],
            options={
                'verbose_name': '项目部署',
                'verbose_name_plural': '项目部署',
            },
        ),
    ]
