# Generated by Django 3.2.1 on 2024-09-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projdep',
            name='Describe',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
