# Generated by Django 3.2.1 on 2024-09-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjManage', '0002_projdep_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projdep',
            name='Describe',
            field=models.TextField(blank=True, null='     ', verbose_name='描述'),
        ),
    ]
