# Generated by Django 3.2.1 on 2024-12-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjManage', '0004_auto_20241126_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projdep',
            name='Group',
            field=models.CharField(choices=[('diylink正式', 'diylink正式'), ('diylink测试', 'diylink测试'), ('TBD_点餐测试', '点餐测试'), ('点餐正式', '点餐正式'), ('其他正式', '其他正式'), ('其他测试', '其他测试')], default='TBD_其他测试', max_length=255, verbose_name='项目组'),
        ),
    ]
