# Generated by Django 3.2.1 on 2024-12-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjManage', '0005_alter_projdep_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projdep',
            name='Group',
            field=models.CharField(choices=[('TBD_diylink正式', 'TBD_diylink正式'), ('TBD_diylink测试', 'TBD_diylink测试'), ('TBD_点餐测试', 'TBD_点餐测试'), ('TBD_点餐正式', 'TBD_点餐正式'), ('TBD_其他正式', 'TBD_其他正式'), ('TBD_其他测试', 'TBD_其他测试'), ('TBD_查看空间', 'TBD_查看空间')], default='TBD_其他测试', max_length=255, verbose_name='项目组'),
        ),
    ]
