# Generated by Django 3.2.1 on 2024-12-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjManage', '0006_alter_projdep_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projdep',
            name='Describe',
            field=models.TextField(null='     ', verbose_name='描述'),
        ),
    ]
