# Generated by Django 3.2.1 on 2024-12-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjManage', '0007_alter_projdep_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projdep',
            name='Describe',
            field=models.TextField(blank=True, default='', null=True, verbose_name='描述'),
        ),
    ]
