# Generated by Django 3.2.1 on 2024-12-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjManage', '0008_alter_projdep_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='projdep',
            name='task_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='任务名'),
        ),
    ]
