# Generated by Django 3.2.1 on 2023-09-28 19:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ConfCen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDeploy',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('发布中', '发布中'), ('已发布', '已发布')], default=0, max_length=255, verbose_name='发布状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('taskdeploy_env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_taskcreate', to='ConfCen.taskcreate', verbose_name='任务选择')),
            ],
            options={
                'verbose_name': '任务发布',
                'verbose_name_plural': '任务发布',
            },
        ),
        migrations.CreateModel(
            name='projectDeploy',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='...', verbose_name='发布内容')),
                ('status', models.CharField(choices=[('发布中', '发布中'), ('已发布', '已发布')], default=0, max_length=255, verbose_name='发布状态')),
                ('task_type', models.CharField(choices=[('发布中', '发布中'), ('已发布', '已发布')], default=0, max_length=255, verbose_name='任务类型')),
                ('version', models.CharField(blank=True, default='1690610777', max_length=255, null=True, verbose_name='发布版本')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deploy_env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_project', to='ConfCen.project', verbose_name='项目选择')),
            ],
            options={
                'verbose_name': '项目部署',
                'verbose_name_plural': '项目部署',
            },
        ),
    ]
