# Generated by Django 3.2.1 on 2023-10-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeployCen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageList',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, default='1690610777', max_length=255, null=True, verbose_name='发布版本')),
                ('package_url', models.CharField(blank=True, default='/static/upload/task_package/1695901740-硬盘读写测试模版.zip', max_length=255, null=True, verbose_name='包连接')),
            ],
        ),
    ]
