# Generated by Django 3.2.1 on 2023-10-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeployCen', '0002_packagelist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageList',
            new_name='VersionList',
        ),
        migrations.AlterModelOptions(
            name='versionlist',
            options={'verbose_name': '版本列表', 'verbose_name_plural': '版本列表'},
        ),
    ]
