# Generated by Django 3.2.1 on 2023-10-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeployCen', '0003_auto_20231007_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdeploy',
            options={'verbose_name': '项目发布', 'verbose_name_plural': '项目发布'},
        ),
        migrations.AlterField(
            model_name='taskdeploy',
            name='status',
            field=models.CharField(default='未发布', max_length=255, verbose_name='发布状态'),
        ),
    ]
