# Generated by Django 3.2.1 on 2023-10-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeployCen', '0004_auto_20231017_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdeploy',
            name='log_id',
            field=models.CharField(default='0', max_length=255, verbose_name='日志id'),
        ),
    ]
