# Generated by Django 3.2.1 on 2023-10-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeployCen', '0005_taskdeploy_log_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdeploy',
            name='version',
            field=models.CharField(default='100', max_length=255, verbose_name='版本号'),
        ),
    ]
