# Generated by Django 3.2.1 on 2023-10-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeployCen', '0006_taskdeploy_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdeploy',
            name='user',
            field=models.CharField(default='admin', max_length=255, verbose_name='创建用户'),
        ),
    ]
