# Generated by Django 3.2.1 on 2023-10-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeployCen', '0007_taskdeploy_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdeploy',
            old_name='user',
            new_name='User',
        ),
    ]
