# Generated by Django 3.2.1 on 2023-10-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeployCen', '0008_rename_user_taskdeploy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdeploy',
            name='User',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='创建用户'),
        ),
    ]
