# Generated by Django 3.2.1 on 2023-10-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeployCen', '0009_alter_taskdeploy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdeploy',
            name='status',
            field=models.CharField(default='等待执行', max_length=255, verbose_name='发布状态'),
        ),
    ]
