# Generated by Django 3.2.1 on 2023-10-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeployCen', '0010_alter_taskdeploy_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskdeploy',
            options={'verbose_name': '任务列表', 'verbose_name_plural': '任务列表'},
        ),
    ]
