# Generated by Django 3.2.1 on 2023-10-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0012_alter_task_type_templates'),
        ('DeployCen', '0011_alter_taskdeploy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdeploy',
            name='task_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_task_type', to='ConfCen.task_type', verbose_name='任务类型'),
        ),
    ]
