# Generated by Django 3.2.1 on 2023-10-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0019_auto_20231023_1632'),
        ('DeployCen', '0012_taskdeploy_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdeploy',
            name='HostGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_HostGroups', to='ConfCen.hostgroup', verbose_name='form_HostGroups'),
        ),
    ]
