# Generated by Django 3.2.1 on 2023-10-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeployCen', '0013_taskdeploy_hostgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdeploy',
            name='HostGroup',
        ),
    ]
