# Generated by Django 3.2.1 on 2023-10-24 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0019_auto_20231023_1632'),
        ('DeployCen', '0015_taskdeploy_select_hostgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdeploy',
            name='select_k8s_Env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_select_k8s_Env', to='ConfCen.k8s_env', verbose_name='select_k8s_Env'),
        ),
    ]
