# Generated by Django 3.2.1 on 2023-10-30 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0025_auto_20231030_0941'),
        ('DeployCen', '0016_taskdeploy_select_k8s_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdeploy',
            name='select_Custom_Env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_select_Custom_Env', to='ConfCen.custom_env', verbose_name='select_Custom_Env'),
        ),
    ]
