# Generated by Django 3.2.1 on 2023-10-30 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0027_alter_custom_env_name'),
        ('DeployCen', '0017_taskdeploy_select_custom_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdeploy',
            name='result',
            field=models.CharField(default='', max_length=255, verbose_name='执行结果'),
        ),
        migrations.AlterField(
            model_name='taskdeploy',
            name='select_Custom_Env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_select_Custom_Env', to='ConfCen.custom_env', verbose_name='自定义配置'),
        ),
        migrations.AlterField(
            model_name='taskdeploy',
            name='status',
            field=models.CharField(default='进行中', max_length=255, verbose_name='发布状态'),
        ),
    ]
