# Generated by Django 3.2.1 on 2023-10-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeployCen', '0019_remove_taskdeploy_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdeploy',
            name='rollBack',
            field=models.CharField(choices=[('否', '否'), ('是', '是')], default=0, max_length=255, verbose_name='是否支持回滚'),
        ),
    ]
