# Generated by Django 3.2.1 on 2023-10-31 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeployCen', '0020_taskdeploy_rollback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdeploy',
            name='rollBack',
        ),
    ]
