# Generated by Django 3.2.1 on 2023-11-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeployCen', '0022_delete_projectdeploy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VersionList',
        ),
    ]
