# Generated by Django 3.2.1 on 2023-11-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0040_auto_20231113_1134'),
        ('DeployCen', '0023_delete_versionlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdeploy',
            name='select_Custom_Env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_select_Custom_Env', to='ConfCen.custom_env', verbose_name='自定义变量配置'),
        ),
    ]
