# Generated by Django 3.2.1 on 2023-11-16 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0042_alter_taskcreate_templategroup'),
        ('DeployCen', '0024_alter_taskdeploy_select_custom_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdeploy',
            name='select_Custom_Env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_select_Custom_Env', to='ConfCen.custom_env', verbose_name='自定义变量配置'),
        ),
    ]
