# Generated by Django 3.2.1 on 2024-02-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeployCen', '0026_taskdeploy_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='monitor',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='进行中', max_length=255, verbose_name='发布状态')),
            ],
        ),
    ]
