# Generated by Django 3.2.1 on 2023-11-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
