# Generated by Django 3.2.1 on 2023-11-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'verbose_name': '应用市场', 'verbose_name_plural': '应用市场'},
        ),
    ]
