# Generated by Django 3.2.1 on 2023-11-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppStore', '0002_alter_app_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='AppMarket',
        ),
    ]
