# Generated by Django 3.2.1 on 2025-01-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AlertGroup',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='报警类名', max_length=255, unique=True, verbose_name='组名')),
                ('message', models.TextField(blank=True, null=True, verbose_name='ai分析内容')),
                ('types', models.CharField(choices=[('未处理', '未处理'), ('已处理', '已处理')], default=0, max_length=255, verbose_name='任务类型')),
                ('group', models.ManyToManyField(to='alarm_analysis.Alert')),
            ],
            options={
                'verbose_name': '模版组',
                'verbose_name_plural': '模版组',
            },
        ),
    ]
