# Generated by Django 3.2.1 on 2025-01-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='is_sent',
        ),
    ]
