# Generated by Django 3.2.1 on 2024-10-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebManger',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='集群名字')),
                ('username', models.CharField(default='', max_length=255, unique=True, verbose_name='用户')),
                ('password', models.CharField(default='', max_length=255, unique=True, verbose_name='密码')),
                ('url', models.CharField(default='', max_length=255, unique=True, verbose_name='链接')),
            ],
            options={
                'verbose_name': '网站管理',
                'verbose_name_plural': '网站管理',
            },
        ),
    ]
