# Generated by Django 3.2.1 on 2024-10-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmanger',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='网站名字'),
        ),
    ]
