# Generated by Django 3.2.1 on 2024-10-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0002_alter_webmanger_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmanger',
            name='url',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='网站链接'),
        ),
        migrations.AlterField(
            model_name='webmanger',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='用户名称'),
        ),
    ]
