# Generated by Django 3.2.1 on 2024-11-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0003_auto_20241029_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmanger',
            name='password',
            field=models.CharField(default='', max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='webmanger',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='用户名称'),
        ),
    ]
