# Generated by Django 3.2.1 on 2024-04-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='node',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('types', models.CharField(choices=[('正式集群', '正式集群'), ('测试集群', '测试集群')], default=0, max_length=255, verbose_name='类型')),
            ],
            options={
                'verbose_name': '集群创建',
                'verbose_name_plural': '集群创建',
            },
        ),
    ]
