# Generated by Django 3.2.1 on 2024-04-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': '添加节点', 'verbose_name_plural': '添加节点'},
        ),
    ]
