# Generated by Django 3.2.1 on 2024-04-03 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0076_taskenc_taskenctaskcreate'),
        ('clusterAdmin', '0002_alter_node_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_node_host', to='ConfCen.hostconfig', verbose_name='主机选择'),
        ),
    ]
