# Generated by Django 3.2.1 on 2024-04-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0003_node_node_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='task_log',
            field=models.CharField(default='0', max_length=255, unique=True, verbose_name='日志id'),
        ),
    ]
