# Generated by Django 3.2.1 on 2024-04-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0004_node_task_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='k8s_cluster',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('types', models.CharField(choices=[('正式集群', '正式集群'), ('测试集群', '测试集群')], default=0, max_length=255, verbose_name='类型')),
            ],
            options={
                'verbose_name': '创建集群',
                'verbose_name_plural': '创建集群',
            },
        ),
        migrations.AlterField(
            model_name='node',
            name='types',
            field=models.CharField(choices=[('node', 'node'), ('master', 'master')], default=0, max_length=255, verbose_name='类型'),
        ),
    ]
