# Generated by Django 3.2.1 on 2024-04-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0005_auto_20240403_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8s_cluster',
            name='select_node_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_select_node_host', to='clusterAdmin.node', verbose_name='node选择'),
        ),
    ]
