# Generated by Django 3.2.1 on 2024-04-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0006_k8s_cluster_select_node_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(default='曼谷node', max_length=255, unique=True, verbose_name='名字'),
        ),
    ]
