# Generated by Django 3.2.1 on 2024-04-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0007_node_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(default='node[曼谷]', max_length=255, unique=True, verbose_name='名字'),
        ),
    ]
