# Generated by Django 3.2.1 on 2024-04-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0008_alter_node_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='task_log',
        ),
    ]
