# Generated by Django 3.2.1 on 2024-04-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0009_remove_node_task_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='k8s_cluster',
            name='select_node_host',
        ),
        migrations.AddField(
            model_name='k8s_cluster',
            name='select_node_host',
            field=models.ManyToManyField(to='clusterAdmin.node'),
        ),
    ]
