# Generated by Django 3.2.1 on 2024-04-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0010_auto_20240403_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='k8s_cluster_list',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '集群列表',
                'verbose_name_plural': '集群列表',
            },
        ),
    ]
