# Generated by Django 3.2.1 on 2024-04-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0011_k8s_cluster_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8s_cluster',
            name='name',
            field=models.CharField(default='集群名字', max_length=255, unique=True, verbose_name='名字'),
        ),
    ]
