# Generated by Django 3.2.1 on 2024-04-03 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0076_taskenc_taskenctaskcreate'),
        ('clusterAdmin', '0012_k8s_cluster_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8s_cluster',
            name='select_kubeconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_select_kubeconfig', to='ConfCen.k8s_env', verbose_name='集群配置'),
        ),
        migrations.AlterField(
            model_name='k8s_cluster',
            name='name',
            field=models.CharField(default='曼谷测试', max_length=255, unique=True, verbose_name='名字'),
        ),
    ]
