# Generated by Django 3.2.1 on 2024-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0013_auto_20240403_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='k8s_network',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '专线创建',
                'verbose_name_plural': '专线创建',
            },
        ),
    ]
