# Generated by Django 3.2.1 on 2024-04-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0014_k8s_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8s_network',
            name='select_node_host',
            field=models.ManyToManyField(to='clusterAdmin.node'),
        ),
    ]
