# Generated by Django 3.2.1 on 2024-04-03 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0015_k8s_network_select_node_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='k8s_network',
            name='select_node_host',
        ),
        migrations.AddField(
            model_name='node',
            name='k8s_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_k8s_network', to='clusterAdmin.k8s_network', verbose_name='专线选择'),
        ),
    ]
