# Generated by Django 3.2.1 on 2024-04-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0016_auto_20240403_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8s_network',
            name='name',
            field=models.CharField(default='专线1', max_length=255, unique=True, verbose_name='名字'),
        ),
    ]
