# Generated by Django 3.2.1 on 2024-04-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0076_taskenc_taskenctaskcreate'),
        ('clusterAdmin', '0017_k8s_network_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8s_network',
            name='k8s_network_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_k8s_network_host', to='ConfCen.hostconfig', verbose_name='主机选择'),
        ),
    ]
