# Generated by Django 3.2.1 on 2024-04-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0018_k8s_network_k8s_network_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='k8s_cluster',
            name='select_kubeconfig',
        ),
        migrations.RemoveField(
            model_name='k8s_cluster',
            name='types',
        ),
    ]
