# Generated by Django 3.2.1 on 2024-04-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0076_taskenc_taskenctaskcreate'),
        ('clusterAdmin', '0019_auto_20240410_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k8s_cluster',
            name='select_node_host',
            field=models.ManyToManyField(to='ConfCen.HostConfig'),
        ),
    ]
