# Generated by Django 3.2.1 on 2024-04-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0020_alter_k8s_cluster_select_node_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='k8s_network',
        ),
        migrations.RemoveField(
            model_name='node',
            name='node_host',
        ),
        migrations.RemoveField(
            model_name='node',
            name='types',
        ),
        migrations.AddField(
            model_name='node',
            name='k8s_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_k8s_cluster', to='clusterAdmin.k8s_cluster', verbose_name='归属集群'),
        ),
    ]
