# Generated by Django 3.2.1 on 2024-04-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterAdmin', '0021_auto_20240410_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k8s_cluster',
            name='Id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
