# Generated by Django 3.2.1 on 2023-09-28 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='配置名')),
                ('config', models.TextField(default='', verbose_name='配置内容')),
            ],
            options={
                'verbose_name': '自定义变量',
                'verbose_name_plural': '自定义变量',
            },
        ),
        migrations.CreateModel(
            name='HiAppstoreTemplates',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='redis-svc.yaml', max_length=255, unique=True, verbose_name='模版名')),
                ('templates', models.TextField(default='\napiVersion: v1\nkind: Service\nmetadata:\n  name: redis-svc\n  namespace:  {{ .Release.Namespace }}\n\nspec:\n  selector:\n    app: redis\n  ports:\n    - protocol: TCP\n      port: 6379\n      targetPort: 6379\n', verbose_name='templates内容')),
            ],
            options={
                'verbose_name': '商店模版',
                'verbose_name_plural': '商店模版',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='主机名')),
                ('internal_ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='内网 IP 地址')),
                ('external_ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='外网 IP 地址')),
                ('ssh_username', models.CharField(max_length=255, verbose_name='SSH 用户名')),
                ('ssh_password', models.CharField(max_length=255, verbose_name='SSH 密码')),
                ('os_version', models.CharField(blank=True, max_length=255, null=True, verbose_name='操作系统版本')),
            ],
            options={
                'verbose_name': '主机配置',
                'verbose_name_plural': '主机配置',
            },
        ),
        migrations.CreateModel(
            name='HostConfig',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='test', max_length=255, verbose_name='主机名')),
                ('user', models.CharField(default='ubuntu', max_length=255, verbose_name='用户')),
                ('port', models.CharField(default='22', max_length=255, verbose_name='端口')),
                ('ip', models.CharField(default='43.229.28.21', max_length=255, unique=True, verbose_name='ip地址')),
                ('password', models.CharField(default='7H2W4EupGqKXbpZR', max_length=255, verbose_name='密码')),
                ('host_key', models.TextField(default='\n-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtz\nc2gtZWQyNTUxOQAAACAPt7r7LqglSQ/wuxb1A7A1T+QkK3WAgiYX1zsgTfhWeQAA\nAIh9yMSsfcjErAAAAAtzc2gtZWQyNTUxOQAAACAPt7r7LqglSQ/wuxb1A7A1T+Qk\nK3WAgiYX1zsgTfhWeQAAAEBLUpcmnKqgjubxOsh5TT5hpKkzD/02FJD0csuIzMdF\nGg+3uvsuqCVJD/C7FvUDsDVP5CQrdYCCJhfXOyBN+FZ5AAAAAAECAwQF\n-----END OPENSSH PRIVATE KEY-----\n', verbose_name='密钥')),
                ('types', models.CharField(choices=[('密钥', '密钥'), ('密码', '密码')], default=0, max_length=255, verbose_name='密码类型')),
            ],
            options={
                'verbose_name': '主机配置',
                'verbose_name_plural': '主机配置',
            },
        ),
        migrations.CreateModel(
            name='k8s_Env',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='43.229.28.92[测试环境]', max_length=255, verbose_name='环境名')),
                ('kube_config', models.TextField(default='\napiVersion: v1\nclusters:\n- cluster:\n    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EWXdOVEEyTXprek5Wb1hEVE16TURZd01qQTJNemt6TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkhGCnlEclBSWkRjcHR5Y3hwZ1BPLzh4T1NzY3IyN0NtODVHRjduRWRYc3A4TE1kRHF0WFBHU1NGOEF0WUJ3M3hGSE0KcHErMnB1TVhTSXZuaDZobXFBUnBxREpOOWxFb0d3ckxlUzVBL2V2clhKcmZxejRHVnEweGNqZjZ1ODB1d3A1TQpaWEJERFhwKzh5Q3Q2NllhUDlQeWR1RHJOWnBoekd3V0k2OFlnU1hhTVFWajM2ODFpNE9KUVVRd3ByeHpGNG8zCmRvbEVuWk4ya2MwbzFCanYwQm4vd1dLNm1hQnNaOGxBNzRtVGVkVGlxRXltdFNKWEJ4WkthNDVTcGg4dVR2SHIKbkpVaHM2bktXQ2NNb3R4OVRNMVl5blBLZmx0UjJ4YjlNNzFWdkpFdW9JVm1vR2c0RVA0WG9rU2lsMDFMRkNOcgpYemZkVm15VkJqVnAzaWREUHcwQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZGSFcxQ1lwdGo0VjBEcmFnWHN5RHY5clFKRFVNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS0RxVUxaOHNnNGdUMGlQVmYwZgpQekdhdlhDMjRjYVUyeURoOGlJTDBRMVlCVXhManl3V2tmQ2tSazlqalJWWllZcXpvMi9uTGZHR1JSdUh0ai9LCk9ES1V6b01rSENzVTB5TmdtWURGM0x3QXNjUnFlcFUrOU50UXcxTlhQcDFkWDNoS0tFSzdrdzNyeFdpMktxdDIKWDJ5eGhyTWYyMEtFVHNaTDE3eEt3b1JQWTZIK2srenIwTFJHMmlkeTQwa0VsWmZ6VzVpak5zY1JDVGEwUnVYRAprLzB6cUYyRUZBbnQxcEoza3BtQ2JSZk91dWdvdGI4WUMrV0Exb25mcE9IMmkrT1N2RmRORERHSHRKZ0h5TTBwCjdyeWlCMmlhRnBmSlR4R2VaYmQzeFNja0NNZUEyY01vN0Z1eHNnWTFLTWs3ei9qYXY2YXN2VDl2WWhIVzNWaVgKTlVnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==\n    server: https://43.229.28.92:6443\n  name: kubernetes\ncontexts:\n- context:\n    cluster: kubernetes\n    user: kubernetes-admin\n  name: kubernetes-admin@kubernetes\ncurrent-context: kubernetes-admin@kubernetes\nkind: Config\npreferences: {}\nusers:\n- name: kubernetes-admin\n  user:\n    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJVFBCZ3ZwSi9PV0l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpBMk1EVXdOak01TXpWYUZ3MHlOREEyTURRd05qTTVOREJhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTYrNENnN2hZTTVaMU45aXYKWGc2SEhhWFYxd1k2bFhJWS9rZ0dCZnczZ2xVQ2JpWmt4SU9ESEx1M2FTQkVIZGxJV3ZqU0dYWWJrUEI2ZHp1VQpMOVhENlNQRHFsaXRjVjBqUHpYcG0zL0RhVmQrRHc3UURUZ0RlaUhjdkpWV2hid2tOTFVFQ3B6OTNNT2V3WGhhCnBoV3ZQL0paRlZoUVJYRjJFZlpCeFBUTVA0RTRlNUxaa1BUL3UyZnE3VUhhTXFoVXdMdzhKdTZZOTBheVZjODYKdCtZVk1tNnhSZ1RhN1pvZVV4OURUdzRDb1dxNldwRW8yS0IyeXk3SjIwQTZEN1pKTnJRalJMK1c4c21KMmdhNQpnck90a3Jqbk9YQmc4WERqSDdMS0JERUxvN0VBNXFYMW5TVDdNQlJMbDFpR0poTEt1OTdEa1VEeDBDTGp6WDJ3CnB5NjFVd0lEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JSUjF0UW1LYlkrRmRBNjJvRjdNZzcvYTBDUQoxREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBcDhKajhuQzhTblVTcTgrdThFd05UUzFXN0NHcW5aNnIxOS91CmVvYmJhd3Z0azhNdktzZ21tRytLUjBER090b1cvNE9KeTAzWGtmRFM3KzgzMWpLYUhJTHMrZVlUUzc3WXRQQzcKRXdDT2lIeGo3bENrQzAwSEUzY3BoTmR3UUxaSFk2Y0l5cWdmZW1VOVJXRW5pR2hTd0JYYUV2RlQxQVVKL0pFZgpyNmZ5MUVCeGhkWTI5UU1WWEpkNHorejNld2dEZDhFSzlwR1Y3ZXBFQVcxVEVacmdESHdVSzB0VUNLMkZDRm0wCkQxMmFWbERqL0Rmd2FWZjdyekFvN3dWVVFtU2hiYzZ0SEcxZy85VCtJZDluKys1VWdUZnE3L2dkdVhxMzVMdFQKMXhUN1pHbmNSeXAyMkhsa2tiR1hCdUJacmpYZm56c2tGZzd1OW93bWlYcXlWOExIZVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==\n    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBNis0Q2c3aFlNNVoxTjlpdlhnNkhIYVhWMXdZNmxYSVkva2dHQmZ3M2dsVUNiaVprCnhJT0RITHUzYVNCRUhkbElXdmpTR1hZYmtQQjZkenVVTDlYRDZTUERxbGl0Y1YwalB6WHBtMy9EYVZkK0R3N1EKRFRnRGVpSGN2SlZXaGJ3a05MVUVDcHo5M01PZXdYaGFwaFd2UC9KWkZWaFFSWEYyRWZaQnhQVE1QNEU0ZTVMWgprUFQvdTJmcTdVSGFNcWhVd0x3OEp1Nlk5MGF5VmM4NnQrWVZNbTZ4UmdUYTdab2VVeDlEVHc0Q29XcTZXcEVvCjJLQjJ5eTdKMjBBNkQ3WkpOclFqUkwrVzhzbUoyZ2E1Z3JPdGtyam5PWEJnOFhEakg3TEtCREVMbzdFQTVxWDEKblNUN01CUkxsMWlHSmhMS3U5N0RrVUR4MENManpYMndweTYxVXdJREFRQUJBb0lCQUNGaXl1Uk0zOTVjK2pWdQo2bElMQ0QrL3llVGxzc0NYSnNaRTl1VTk3YlQ1eHFCRHVwcThhWDlWYVB6dFhmWkRXeVBVZGhhNFNlcFd2VjNHCkJwQkdWYlRXSk1na1NGYjBjUnB1ektIK2tHNkZ2UWJ3ZDZ5SE1xYkR4L0sveDBDaGdSWWNUM2daQXl1TVd4alIKcVRJN2UxTTNQamZ4Q1ZycVZXVHhUaGxLOHVSQlpXaWcxcThIMm1mV1NsMlZvcTBVaCtSY2djY0xNY1JXL0xYNgo5N1hHTWR1cXBhVll6SEJSSGFvYWtZL1lhM0JWd2hWenZGdVcwMy91MXkwQTEzQTdLQlN1czd3YmtaaFBmQkVnCm51aGNKTkZSd2pmZ2c1L21LcXRSanJFYkM1YmxJVDRKVXlGZ2l4UUl3aVFIY3ZKMTFTQXVWemIwb3o3YzVCblYKa0ZCMEFuRUNnWUVBOW0waUtxU3QxakRvbVNEOUNMUGVjdWZxYU56YWJyNXJjbGZ6OFdob0xyL2djSUNWcEo3dQpBNG4xT2tzejk0Y2ppSjROUDBnY1JTNUI0dWJRWndnZVIwTGZqZDRySzZzTllYdWE5Zzg0dm9RT09aOVVnOTVNCmJac0NKOU1FV0l3Rm5adDBYc2tWQ28zT2ZLUWZobXNrU2pIS1BsYWhMWVBkSitoU1ZDRWlFTmNDZ1lFQTlSaDcKTVJ0M1ViMjJGSk5aWjEyVFFTcXVwMmxNdXhuZEp6dFA1UG9XWlNkblM0bDNWV24xRnh1L3hOSlVvQWlGOUUvQwpvazg2UzVoVmI0dER6N0FFYllDVzU1Vk9GNWFLMksvSFdrN0xBaDV3dU80QlJGdVV5cmY0MkhGLzB1VGJzUEI0Cm5CdmxvMU9iQzMzY2picGJxUE9LMlJ3SytiS3QvdGUxTmtPUjQrVUNnWUFLZnBWUTZaaDVvYldXSitCK3lXSTAKMUltWUU2ZTl4YUEveTEwWkw5QVlCWlhpVktlS3pqWG1zcTVkNEN3RFk1N3d4NEphNnBCQnBmbXFWeGdTK3phRwo1R011NElKSUpzMjRGQktDWGgyVmgzd3ZtZ2g0WVRReUNzTHB2VVBYSFlkenNkWWYzMEpsSTZyaWhmN05zNnhrCitIL2JiY2NKY0M4djd1WHFyVXFOR3dLQmdGUWRuc252dnplU2dGYjNhd3VLbGVzYmx1MWx1aXZNYUpYNlNTVXcKbjFiLyt2ZDFxanJxTG05TDJyalY1cTAxdjZObGJFc0FIZVdyMWtaOTZUdnlFTkx6K3RabjYzRTAvVm40bWRabwpqRXVoM3RYWStSNVl2K3dDejZpWTYyR1pvYnhNQzFpb1NsdVBhZnE3cTJJSXYwUndzUXBxRVdvNDVIWTkyYmRSCjRWUHhBb0dBQlVEOExXcGVHcEE3MkVmU2ZSeDQyMW9CQlVYUDJpSzNzVXZ6OGFkN2ZjTTgzVzNrWUgxOURqR0IKU0hXOWFvRGRRUThqd1IxVng3VlA2SkwxM3lUMXh3bUF2NWtjcmlEcGJJTmRUbVVmdUFsYzhiNk1sV2lMV21LZgpqNzBZZ01GbTZiWGFtU1RRUE5zUWJOckw5VWt3Y1MrU1dDNWlMaW1MeFdvMXN0NElYckU9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==\n', verbose_name='配置')),
            ],
            options={
                'verbose_name': '集群配置',
                'verbose_name_plural': '集群配置',
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='io硬盘测试', max_length=255, unique=True, verbose_name='pipeline名')),
                ('templates', models.TextField(default='', verbose_name='pipeline')),
            ],
            options={
                'verbose_name': 'pipeline',
                'verbose_name_plural': 'pipeline',
            },
        ),
        migrations.CreateModel(
            name='Task_type',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='任务类型')),
                ('templates', models.TextField(default='', verbose_name='templates内容')),
            ],
            options={
                'verbose_name': '任务计划模版',
                'verbose_name_plural': '任务计划模版',
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='', verbose_name='日志名字')),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='pipeline', max_length=255, unique=True, verbose_name='模版名')),
                ('templates', models.TextField(default='', verbose_name='templates内容')),
            ],
            options={
                'verbose_name': '模版配置',
                'verbose_name_plural': '模版配置',
            },
        ),
        migrations.CreateModel(
            name='TemplatesGroup',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='helm发布', max_length=255, unique=True, verbose_name='模版组')),
                ('group', models.ManyToManyField(to='ConfCen.Templates')),
            ],
            options={
                'verbose_name': '模版组',
                'verbose_name_plural': '模版组',
            },
        ),
        migrations.CreateModel(
            name='TaskCreate',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='io硬盘测试', max_length=255, unique=True, verbose_name='任务名')),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_pipeline', to='ConfCen.pipeline', verbose_name='pipeline')),
                ('templateGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_templateGroup', to='ConfCen.templatesgroup', verbose_name='模版组')),
            ],
            options={
                'verbose_name': '任务创建',
                'verbose_name_plural': '任务创建',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='helm-deploy', max_length=255, unique=True, verbose_name='任务名')),
                ('pipeline', models.TextField(default='', verbose_name='pipeline')),
                ('task_log', models.ManyToManyField(to='ConfCen.TaskLog')),
            ],
            options={
                'verbose_name': '任务配置',
                'verbose_name_plural': '任务配置',
            },
        ),
        migrations.CreateModel(
            name='pTemp',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='php项目', max_length=255, verbose_name='模版名字')),
                ('init_shell', models.TextField(default='#!/bin/bash\n', verbose_name='初始化脚本')),
                ('deploy_config', models.TextField(default='apiVersion: tekton.dev/v1\nkind: Task\nmetadata:\n  name: build-php\nspec:\n  steps:\n    - name: git-pull\n      image: huangchengwu6904/hi-app:hi-tools-1\n      workingDir: /workspace/git-repo\n      script: |\n            #!/usr/bin/env sh\n            git clone  git@github.com:huangchengwu/dws_cmdb.git  .\n    - name: build-ci\n      image:  docker:dind\n      securityContext:\n        privileged: true  \n      workingDir: /workspace/git-repo\n      script: |\n            #!/usr/bin/env sh\n            nohup dockerd &\n            cat >Dockerfile<<EOF\n            FROM huangchengwu6904/hi-app:dws_cmdb-base\n            COPY . /dws_cmdb\n            EOF\n            time=`date -u +%s`\n            echo "Qq751164212." | docker login --username huangchengwu6904 --password-stdin\n            docker build -t huangchengwu6904/hi-app:dws_cmdb-${time} .\n            docker push huangchengwu6904/hi-app:dws_cmdb-${time}\n            docker rmi  huangchengwu6904/hi-app:dws_cmdb-${time}\n            echo "huangchengwu6904/hi-app:dws_cmdb-${time}" >version\n\n            \n    - name: helm-deploy-cd\n      image: huangchengwu6904/hi-app:hi-tools-1\n      workingDir: /workspace/git-repo\n      script: |\n            #!/usr/bin/env sh\n        \n            ln -s /etc/k8s_config/43.229.28.92  ~/.kube/config\n            helm status my-haitun-cmdb  -n haitun-cmdb &&  helm  upgrade  my-haitun-cmdb  ./helm/dws_cmdb  --set cmdb.image=`cat version`  --namespace  haitun-cmdb  ||  helm install my-haitun-cmdb  ./helm/dws_cmdb --set cmdb.image=`cat version`   --namespace  haitun-cmdb\n\n', verbose_name='部署配置')),
                ('deploy_env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_env', to='ConfCen.k8s_env', verbose_name='部署环境')),
            ],
            options={
                'verbose_name': '项目模版',
                'verbose_name_plural': '项目模版',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='cloud7', max_length=255, unique=True, verbose_name='项目')),
                ('version', models.CharField(blank=True, default='1690610777', max_length=255, null=True, verbose_name='当前版本')),
                ('domain', models.CharField(default='pwf.keli.vip', max_length=255, verbose_name='部署域名')),
                ('dockerfile', models.TextField(default='', verbose_name='dockerfile')),
                ('cmd', models.TextField(default='', verbose_name='shell')),
                ('configmap', models.TextField(default='\napiVersion: v1\nkind: ConfigMap\nmetadata:\n      name: conf\n      namespace: {{ namespace }} \n\n', verbose_name='configmap')),
                ('values', models.TextField(default='\nstorageClassName:   csi-cephfs-sc\nredis:\n  image: redis:alpine\n  storage: 8Gi\n  password: idc123456\n', verbose_name='values.yaml')),
                ('env_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_env_template', to='ConfCen.templatesgroup', verbose_name='部署模版')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='内网测试', max_length=255, unique=True, verbose_name='组名')),
                ('Host', models.ManyToManyField(to='ConfCen.HostConfig')),
            ],
            options={
                'verbose_name': '主机组',
                'verbose_name_plural': '主机组',
            },
        ),
        migrations.CreateModel(
            name='HiAppstore',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='cloud7', max_length=255, unique=True, verbose_name='应用名字')),
                ('chart', models.TextField(default='\napiVersion: v2\nname: redis\ndescription: A Helm chart for Kubernetes\ntype: application\nversion: 0.1.0\nappVersion: "1.16.0"\n', verbose_name='chart')),
                ('values', models.TextField(default='\nstorageClassName:   csi-cephfs-sc\nredis:\n  image: redis:alpine\n  storage: 8Gi\n  password: idc123456\n', verbose_name='values')),
                ('configmap', models.TextField(default='\napiVersion: v1\nkind: ConfigMap\nmetadata:\n      name: conf\n      namespace: {{ namespace }} \n\n', verbose_name='configmap')),
                ('templates', models.ManyToManyField(to='ConfCen.HiAppstoreTemplates')),
            ],
            options={
                'verbose_name': '应用商店',
                'verbose_name_plural': '应用商店',
            },
        ),
    ]
