# Generated by Django 3.2.1 on 2023-10-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目配置', 'verbose_name_plural': '项目配置'},
        ),
    ]
