# Generated by Django 3.2.1 on 2023-10-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0003_task_pacakge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pacakge',
            field=models.FileField(upload_to='uploads/', verbose_name='压缩包'),
        ),
    ]
