# Generated by Django 3.2.1 on 2023-10-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0004_alter_task_pacakge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='pacakge',
        ),
    ]
