# Generated by Django 3.2.1 on 2023-10-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0005_remove_task_pacakge'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='pacakge',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='压缩包'),
        ),
    ]
