# Generated by Django 3.2.1 on 2023-10-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0006_pipeline_pacakge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='pacakge',
            field=models.FileField(blank=True, null=True, upload_to='pipeline/uploads/', verbose_name='其他压缩包'),
        ),
    ]
