# Generated by Django 3.2.1 on 2023-10-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0007_alter_pipeline_pacakge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='io硬盘测试', max_length=255, unique=True, verbose_name='pipeline名')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Test',
            },
        ),
    ]
