# Generated by Django 3.2.1 on 2023-10-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
