# Generated by Django 3.2.1 on 2023-10-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0009_delete_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task_type',
            options={'verbose_name': '任务计划', 'verbose_name_plural': '任务计划'},
        ),
    ]
