# Generated by Django 3.2.1 on 2023-10-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0010_alter_task_type_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_type',
            name='types',
            field=models.CharField(choices=[('一次性', '一次性'), ('周期性', '周期性')], default=0, max_length=255, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='task_type',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='名字'),
        ),
    ]
