# Generated by Django 3.2.1 on 2023-10-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0011_auto_20231019_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_type',
            name='templates',
            field=models.TextField(blank=True, null=True, verbose_name='templates内容'),
        ),
    ]
