# Generated by Django 3.2.1 on 2023-10-20 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0012_alter_task_type_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcreate',
            name='HostGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_HostGroup', to='ConfCen.hostgroup', verbose_name='HostGroup'),
        ),
    ]
