# Generated by Django 3.2.1 on 2023-10-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0014_auto_20231020_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcreate',
            name='k8s_Env',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_k8s_Env', to='ConfCen.k8s_env', verbose_name='form_k8s_Env'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='name',
            field=models.CharField(default='hosts', max_length=255, unique=True, verbose_name='模版名'),
        ),
    ]
