# Generated by Django 3.2.1 on 2023-10-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0016_auto_20231023_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcreate',
            name='help',
            field=models.CharField(blank=True, default='帮助文档', max_length=255, null=True, verbose_name='帮助文档'),
        ),
    ]
