# Generated by Django 3.2.1 on 2023-10-23 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0018_alter_taskcreate_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcreate',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_pipeline', to='ConfCen.pipeline', verbose_name='form_pipeline'),
        ),
        migrations.AlterField(
            model_name='taskcreate',
            name='templateGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_templateGroup', to='ConfCen.templatesgroup', verbose_name='form_templateGroup'),
        ),
    ]
