# Generated by Django 3.2.1 on 2023-10-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0021_remove_taskcreate_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcreate',
            name='help',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='帮助文档'),
        ),
    ]
