# Generated by Django 3.2.1 on 2023-10-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0022_taskcreate_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcreate',
            name='help',
        ),
    ]
