# Generated by Django 3.2.1 on 2023-10-27 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doc', '0001_initial'),
        ('ConfCen', '0023_remove_taskcreate_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcreate',
            name='help',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_help', to='Doc.helpdocuments', verbose_name='帮助文档'),
        ),
    ]
