# Generated by Django 3.2.1 on 2023-10-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0025_auto_20231030_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_env',
            old_name='kube_config',
            new_name='config',
        ),
    ]
