# Generated by Django 3.2.1 on 2023-10-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0026_rename_kube_config_custom_env_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_env',
            name='name',
            field=models.CharField(blank=True, default='custom.yaml', max_length=255, verbose_name='配置名'),
        ),
    ]
