# Generated by Django 3.2.1 on 2023-10-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0027_alter_custom_env_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcreate',
            name='rollBack',
            field=models.CharField(choices=[('是', '是')], default=0, max_length=255, verbose_name='是否支持回滚'),
        ),
    ]
