# Generated by Django 3.2.1 on 2023-10-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0029_alter_taskcreate_rollback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcreate',
            name='rollBack',
            field=models.CharField(choices=[('否', '否'), ('是', '是')], default=0, max_length=255, verbose_name='是否支持回滚'),
        ),
    ]
