# Generated by Django 3.2.1 on 2023-11-03 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0030_alter_taskcreate_rollback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('SECRET', models.CharField(default='q5smMgRhHnQ/SZbwm5qxPsdljoMmC75cwKI/kTaSrfE=', max_length=255, unique=True, verbose_name='SECRET')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Webhook_SECRET',
                'verbose_name_plural': 'Webhook_SECRET',
            },
        ),
    ]
