# Generated by Django 3.2.1 on 2023-11-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0031_webhook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhook',
            options={'verbose_name': 'Webhook', 'verbose_name_plural': 'Webhook'},
        ),
        migrations.AddField(
            model_name='webhook',
            name='url',
            field=models.CharField(default='http://cmdb.keli.vip/Webhook/?taskdeploy_env=18&task_type=1&select_HostGroup=7', max_length=255, unique=True, verbose_name='SECRET'),
        ),
    ]
