# Generated by Django 3.2.1 on 2023-11-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0032_auto_20231103_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='desc',
            field=models.CharField(default='烤肉更新', max_length=255, unique=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.CharField(default='http://cmdb.keli.vip/Webhook/?taskdeploy_env=18&task_type=1&select_HostGroup=7', max_length=255, unique=True, verbose_name='url'),
        ),
    ]
