# Generated by Django 3.2.1 on 2023-11-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0033_auto_20231103_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='desc',
        ),
    ]
