# Generated by Django 3.2.1 on 2023-11-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0034_remove_webhook_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='SECRET',
            field=models.CharField(default='q5smMgRhHnQ/SZbwm5qxPsdljoMmC75cwKI/kTaSrfE=', max_length=255, verbose_name='SECRET'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.CharField(default='http://cmdb.keli.vip/Webhook/?taskdeploy_env=18&task_type=1&select_HostGroup=7', max_length=255, verbose_name='url'),
        ),
    ]
