# Generated by Django 3.2.1 on 2023-11-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0035_auto_20231103_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostconfig',
            name='types',
            field=models.CharField(choices=[('密码', '密码'), ('密钥', '密钥')], default=0, max_length=255, verbose_name='密码类型'),
        ),
    ]
