# Generated by Django 3.2.1 on 2023-11-09 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0036_alter_hostconfig_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcreate',
            name='task_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pks_task_type', to='ConfCen.task_type', verbose_name='任务类型'),
        ),
    ]
