# Generated by Django 3.2.1 on 2023-11-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0037_taskcreate_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='任务名'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='name',
            field=models.CharField(default='hellowold', max_length=255, unique=True, verbose_name='pipeline名'),
        ),
    ]
