# Generated by Django 3.2.1 on 2023-11-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0038_auto_20231113_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcreate',
            name='custom',
            field=models.TextField(default='', verbose_name='自定义变量配置'),
        ),
        migrations.AlterField(
            model_name='taskcreate',
            name='name',
            field=models.CharField(default='hellowolrd', max_length=255, unique=True, verbose_name='任务名'),
        ),
    ]
