# Generated by Django 3.2.1 on 2023-11-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0039_auto_20231113_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcreate',
            name='custom',
        ),
        migrations.AddField(
            model_name='taskcreate',
            name='LocalVariable',
            field=models.TextField(default='', verbose_name='局部变量配置'),
        ),
    ]
