# Generated by Django 3.2.1 on 2023-11-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0040_auto_20231113_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcreate',
            name='LocalVariable',
        ),
    ]
