# Generated by Django 3.2.1 on 2023-11-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0041_remove_taskcreate_localvariable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcreate',
            name='templateGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_templateGroup', to='ConfCen.templatesgroup', verbose_name='form_templateGroup'),
        ),
    ]
