# Generated by Django 3.2.1 on 2023-11-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0042_alter_taskcreate_templategroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcreate',
            name='agent_celery',
            field=models.CharField(choices=[('否', '否'), ('是', '是')], default=0, max_length=255, verbose_name='是否开启agent_celery'),
        ),
    ]
