# Generated by Django 3.2.1 on 2023-11-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0043_taskcreate_agent_celery'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTaskCreate',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='hellowolrd', max_length=255, unique=True, verbose_name='任务名')),
                ('config', models.TextField(default='', verbose_name='配置内容')),
            ],
            options={
                'verbose_name': '一键配置任务',
                'verbose_name_plural': '一键配置任务',
            },
        ),
    ]
