# Generated by Django 3.2.1 on 2023-11-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0044_autotaskcreate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autotaskcreate',
            old_name='config',
            new_name='templates',
        ),
    ]
