# Generated by Django 3.2.1 on 2023-11-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0045_rename_config_autotaskcreate_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotaskcreate',
            name='Task_type',
            field=models.CharField(choices=[('主机类型', '主机类型'), ('k8s类型', 'k8s类型')], default=0, max_length=255, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='autotaskcreate',
            name='templates',
            field=models.TextField(default='', verbose_name='pipeline'),
        ),
    ]
