# Generated by Django 3.2.1 on 2023-11-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0046_auto_20231123_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotaskcreate',
            name='Task_type',
            field=models.CharField(choices=[('否', '否'), ('是', '是')], default=0, max_length=255, verbose_name='自定义配置'),
        ),
    ]
