# Generated by Django 3.2.1 on 2023-11-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0047_alter_autotaskcreate_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotaskcreate',
            name='Custom_Task_type',
            field=models.CharField(choices=[('否', '否'), ('是', '是')], default=0, max_length=255, verbose_name='自定义配置'),
        ),
        migrations.AlterField(
            model_name='autotaskcreate',
            name='Task_type',
            field=models.CharField(choices=[('主机类型', '主机类型'), ('k8s类型', 'k8s类型')], default=0, max_length=255, verbose_name='任务类型'),
        ),
    ]
