# Generated by Django 3.2.1 on 2023-11-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0048_auto_20231123_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autotaskcreate',
            options={'verbose_name': '一键新增任务', 'verbose_name_plural': '一键新增任务'},
        ),
        migrations.RemoveField(
            model_name='autotaskcreate',
            name='Task_type',
        ),
        migrations.AlterField(
            model_name='custom_env',
            name='name',
            field=models.CharField(blank=True, default='custom.yaml', max_length=255, unique=True, verbose_name='配置名'),
        ),
    ]
