# Generated by Django 3.2.1 on 2023-12-13 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0049_auto_20231123_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostconfig',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='hostconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
