# Generated by Django 3.2.1 on 2023-12-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0050_auto_20231213_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hostconfig',
            name='updated_at',
        ),
    ]
