# Generated by Django 3.2.1 on 2024-02-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0051_auto_20231213_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='web_monitor',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, default='https://www.baidu.com', max_length=255, verbose_name='网站')),
            ],
            options={
                'verbose_name': '监控配置',
                'verbose_name_plural': '监控配置',
            },
        ),
    ]
