# Generated by Django 3.2.1 on 2024-02-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0052_web_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_monitor',
            name='host',
            field=models.CharField(blank=True, default='172.0.0.1', max_length=255, verbose_name='主机'),
        ),
    ]
