# Generated by Django 3.2.1 on 2024-02-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0053_web_monitor_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_monitor',
            name='monitor_status',
            field=models.CharField(choices=[('已启动', '已启动'), ('未启动', '未启动')], default=0, max_length=255, verbose_name='监控状态'),
        ),
    ]
