# Generated by Django 3.2.1 on 2024-02-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0054_web_monitor_monitor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_monitor',
            name='certificate_effective',
            field=models.CharField(blank=True, default=0, max_length=255, verbose_name='证书有效时间'),
        ),
    ]
