# Generated by Django 3.2.1 on 2024-02-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0055_web_monitor_certificate_effective'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_monitor',
            name='monitor_p',
            field=models.CharField(blank=True, default='1分钟', max_length=255, verbose_name='监控频率'),
        ),
    ]
