# Generated by Django 3.2.1 on 2024-02-29 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0056_web_monitor_monitor_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_monitor',
            name='monitor_p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_p', to='ConfCen.task_type', verbose_name='监控频率'),
        ),
    ]
