# Generated by Django 3.2.1 on 2024-02-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0057_alter_web_monitor_monitor_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_monitor',
            name='monitor_p',
        ),
    ]
