# Generated by Django 3.2.1 on 2024-02-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0059_web_monitor_monitor_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_monitor',
            name='certificate_path',
            field=models.CharField(blank=True, default='/etc/nginx/ssl/', max_length=255, verbose_name='证书路径'),
        ),
    ]
