# Generated by Django 3.2.1 on 2024-02-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0060_web_monitor_certificate_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_monitor',
            name='host',
        ),
        migrations.RemoveField(
            model_name='web_monitor',
            name='monitor_p',
        ),
    ]
