# Generated by Django 3.2.1 on 2024-02-29 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0061_auto_20240229_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_monitor',
            name='monitor_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_monitor_host', to='ConfCen.hostconfig', verbose_name='form_monitor_host'),
        ),
    ]
