# Generated by Django 3.2.1 on 2024-03-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0062_web_monitor_monitor_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_monitor',
            name='web_code',
            field=models.CharField(choices=[('已启动', '已启动'), ('未启动', '未启动')], default=0, max_length=255, verbose_name='web状态码'),
        ),
    ]
