# Generated by Django 3.2.1 on 2024-03-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0063_web_monitor_web_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_monitor',
            name='web_code',
            field=models.CharField(blank=True, default='0', max_length=255, verbose_name='web状态码'),
        ),
    ]
