# Generated by Django 3.2.1 on 2024-03-06 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0064_alter_web_monitor_web_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_monitor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='web_monitor',
            name='describe',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='描述信息'),
        ),
        migrations.AddField(
            model_name='web_monitor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='web_monitor',
            name='user',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='创建用户'),
        ),
        migrations.AlterField(
            model_name='web_monitor',
            name='monitor_status',
            field=models.CharField(choices=[('已启动', '已启动'), ('未启动', '未启动')], default=1, max_length=255, verbose_name='证书功能'),
        ),
        migrations.AlterField(
            model_name='web_monitor',
            name='url',
            field=models.CharField(blank=True, default='www.baidu.com', max_length=255, verbose_name='网站'),
        ),
    ]
