# Generated by Django 3.2.1 on 2024-03-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0065_auto_20240306_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_monitor',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='web_monitor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
    ]
