# Generated by Django 3.2.1 on 2024-03-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0066_auto_20240306_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_monitor',
            name='web_type_status',
            field=models.CharField(choices=[('http', 'http'), ('https', 'https')], default=1, max_length=255, verbose_name='链接类型'),
        ),
    ]
