# Generated by Django 3.2.1 on 2024-03-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0067_web_monitor_web_type_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_monitor',
            name='user',
        ),
        migrations.AlterField(
            model_name='web_monitor',
            name='monitor_status',
            field=models.CharField(choices=[('未启动', '未启动'), ('本地监控', '本地监控'), ('远程监控', '远程监控')], default=1, max_length=255, verbose_name='证书功能'),
        ),
        migrations.AlterField(
            model_name='web_monitor',
            name='web_type_status',
            field=models.CharField(choices=[('http', 'http'), ('https', 'https')], default=2, max_length=255, verbose_name='链接类型'),
        ),
    ]
