# Generated by Django 3.2.1 on 2024-03-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0068_auto_20240318_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='配置名')),
            ],
            options={
                'verbose_name': '任务封装',
                'verbose_name_plural': '任务封装',
            },
        ),
        migrations.AlterField(
            model_name='web_monitor',
            name='monitor_status',
            field=models.CharField(choices=[('未启动', '未启动'), ('本地模式', '本地模式'), ('远程模式', '远程模式')], default=1, max_length=255, verbose_name='证书功能'),
        ),
    ]
