# Generated by Django 3.2.1 on 2024-03-19 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0069_auto_20240319_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskenc',
            name='TaskButton',
            field=models.TextField(default='', verbose_name='任务按钮'),
        ),
        migrations.AddField(
            model_name='taskenc',
            name='TaskEnc_select_Custom_Env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_TaskEnc_select_Custom_Env', to='ConfCen.custom_env', verbose_name='配置选择'),
        ),
        migrations.AlterField(
            model_name='taskenc',
            name='name',
            field=models.CharField(max_length=255, verbose_name='名字'),
        ),
    ]
