# Generated by Django 3.2.1 on 2024-03-20 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0070_auto_20240319_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskenc',
            name='TaskEnc_select_Custom_Env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_TaskEnc_select_Custom_Env', to='ConfCen.custom_env', verbose_name='配置'),
        ),
    ]
