# Generated by Django 3.2.1 on 2024-03-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0071_alter_taskenc_taskenc_select_custom_env'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskenc',
            name='TaskEnc_select_Custom_Env',
        ),
    ]
