# Generated by Django 3.2.1 on 2024-03-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0072_remove_taskenc_taskenc_select_custom_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskenc',
            name='Custom_Env',
            field=models.TextField(default='', verbose_name='配置模版'),
        ),
    ]
