# Generated by Django 3.2.1 on 2024-03-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0073_taskenc_custom_env'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskenc',
            name='id',
        ),
        migrations.AddField(
            model_name='taskenc',
            name='Id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
