# Generated by Django 3.2.1 on 2024-03-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0074_auto_20240320_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskenc',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
