# Generated by Django 3.2.1 on 2024-03-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0075_alter_taskenc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskenc',
            name='TaskEnctaskcreate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_TaskEnctaskcreate', to='ConfCen.taskcreate', verbose_name='任务选择'),
        ),
    ]
