# Generated by Django 3.2.1 on 2024-11-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0076_taskenc_taskenctaskcreate'),
    ]

    operations = [
        migrations.CreateModel(
            name='consuleManger',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='115-test', max_length=255, unique=True, verbose_name='配置名')),
                ('templates', models.TextField(default='\n- name : "prometheus"\n  port: "30682"\n  server:\n  - "10.255.100.1:30682"\n  - "10.255.100.3:30682"\n', verbose_name='consule_config配置内容')),
            ],
            options={
                'verbose_name': 'consul配置管理',
                'verbose_name_plural': 'consul配置管理',
            },
        ),
    ]
