# Generated by Django 3.2.1 on 2024-11-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0077_consulemanger'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulemanger',
            name='wlan',
            field=models.CharField(default='43.229.28.252', max_length=255, unique=True, verbose_name='外网ip'),
        ),
        migrations.AlterField(
            model_name='consulemanger',
            name='name',
            field=models.CharField(default='115-ingress-wan', max_length=255, unique=True, verbose_name='配置名'),
        ),
        migrations.AlterField(
            model_name='consulemanger',
            name='templates',
            field=models.TextField(default='#以下是prometheus例子port外部端口   server内部主机对应的nodePort端口\n- name : "prometheus"\n  port: "30682"\n  server:\n  - "10.255.100.1:30682"\n  - "10.255.100.3:30682"\n', verbose_name='consule_config配置内容'),
        ),
    ]
