# Generated by Django 3.2.1 on 2024-11-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0078_auto_20241108_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulemanger',
            name='describe',
            field=models.TextField(default='ingress-wan 外网配置请部署到服务器', verbose_name='描述'),
        ),
    ]
